### ISSUE TITLE
Websocket issue?

### ISSUE THREAD

**Issue by pblemel** [seoulrobotics/sensr_sdk#27]
Hi,

I have installed the SENSR software development kit and the SENSR application can see my Ouster LIDAR.  So far, so good.

I am running into a problem with the SDK example "console" application.  Do I need to start some kind of "server process" first?

% python3 console_output.py --address localhost --example_type object
Receiving SENSR output from ws://localhost...
Task exception was never retrieved
future: <Task finished coro=<MessageListener._output_stream() done, defined at /home/discovery/src/sensr_sdk/python/sensr_message_listener.py:36> exception=InvalidMessage('did not receive a valid HTTP response',)>
Traceback (most recent call last):
  File "/home/discovery/.local/lib/python3.6/site-packages/websockets/http.py", line 139, in read_response
    status_line = await read_line(stream)
  File "/home/discovery/.local/lib/python3.6/site-packages/websockets/http.py", line 219, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/discovery/.local/lib/python3.6/site-packages/websockets/client.py", line 101, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/home/discovery/.local/lib/python3.6/site-packages/websockets/http.py", line 141, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/discovery/src/sensr_sdk/python/sensr_message_listener.py", line 37, in _output_stream
    async with websockets.connect(self._output_address, compression=None, max_size=None, ping_interval=None) as websocket:
  File "/home/discovery/.local/lib/python3.6/site-packages/websockets/client.py", line 517, in __aenter__
    return await self
  File "/home/discovery/.local/lib/python3.6/site-packages/websockets/client.py", line 547, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/home/discovery/.local/lib/python3.6/site-packages/websockets/client.py", line 290, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/home/discovery/.local/lib/python3.6/site-packages/websockets/client.py", line 103, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
^CTraceback (most recent call last):
  File "console_output.py", line 131, in <module>
    object_listener.connect()
  File "/home/discovery/src/sensr_sdk/python/sensr_message_listener.py", line 68, in connect
    self._loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

Thanks

**Comment by KangJH** [comment]
Could you tell me the version info of SENSR product and SDK?

**Comment by pblemel** [comment]
> Could you tell me the version info of SENSR product and SDK?

I cloned the SDK from this repository. Since writing this issue, I have been instructed to download a more recent version of the SENSR software, so I will close this issue. 

Thanks
